### ISSUE TITLE
What about hex colors (hex triplet) parsing?

### ISSUE THREAD

**Issue by RazrFalcon** [kornelski/rust-rgb#1]
Like `#0099CC`.

Also it will be useful to be able to convert color to hex.

**Comment by pornel** [comment]
What would be the API for this?

Why in this crate, not a separate one?

**Comment by RazrFalcon** [comment]
`FromStr` trait + `Display` trait (which you already using). 

Also there is [hex](https://crates.io/crates/hex) crate, which provides `FromHex` and `ToHex` traits.

But if you trying to keep this crate as simple as possible, that yes, it's better to make an another crate.

**Comment by pornel** [comment]
`FromStr` makes sense, and it has to live in this crate due to orphan rules.

Now I wonder how advanced should it be. Parsing just `#RRGGBB` is easy, `rgba(255,255,255)` is doable, but from there I can see it scope-creep into parsing CSS color syntax.

**Comment by RazrFalcon** [comment]
I personally need only `#RRGGBB`. Implementing all web/css colors stuff is pretty hard. They also have named colors, which will blow up the size a lot...

From a second thought, I think it really should be done by another crate, because `#RRGGBB` can only be done for `RGB8`, so it's not a crate wide feature.

**Comment by RazrFalcon** [comment]
As for now, I think that this is out of scope. `rgb` should be as slim as possible.

**Comment by hmeine** [comment]
I came across this issue looking for exactly this: A way to parse a hex color string into an RGB8. For a beginner (like me), it would be nice to find code here, so let me drop mine here, even though I am still a bloody beginner:
```
fn parse_hex_color(hex_color: &str) -> Result<RGB8, hex::FromHexError>
{
    if hex_color.len() != 6 {
        return Err(hex::FromHexError::InvalidStringLength);
    }
    hex::decode(hex_color).map(
        |bytes| RGB8::new(bytes[0], bytes[1], bytes[2])
    )
}

#[test]
fn test_parse_hex_color() {
    assert_eq!(parse_hex_color("ffffff").unwrap(), RGB8::new(255, 255, 255));
    assert_eq!(parse_hex_color("000000").unwrap(), RGB8::new(0, 0, 0));
    assert_eq!(parse_hex_color("112233").unwrap(), RGB8::new(0x11, 0x22, 0x33));
    assert!(parse_hex_color("12").is_err());
    assert!(parse_hex_color("zzoo").is_err());
    assert!(parse_hex_color("12345678").is_err());
}
```

**Comment by kornelski** [comment]
If you need to parse colors, check out https://lib.rs/crates/css-color-parser2
