### ISSUE TITLE
Time to switch the default branch, and make another one?

### ISSUE THREAD

**Issue by ripytide** [kornelski/rust-rgb#101]
I think I'm getting to near the point on `v0.9` where I'm wanting to publish an alpha release of `v0.9`. I may need another day or two to do a once-over of all of the tracking issues again to make sure we haven't missed anything.

Based on this I think it might be time to move the `0.9` branch over to `main` and move the current `main` branch to a `v0.8` branch. It might also be worth creating another `v0.8-semver` branch for all of the work needed for the last `v0.8` semver-trick releases.

**Comment by kornelski** [comment]
I've been busy recently and haven't had time to properly try out the new APIs. 
I'd like to first try converting a couple of my crates to see if there aren't any blockers before publicizing the new version.

**Comment by ripytide** [comment]
Take all the time you need, in fact I'm highly impressed at your responsiveness in general, it has made my work much more pleasant, thanks!

Regarding your test migrations: that sounds excellent! When doing a test migration it might be a good idea to write up a migration guide too so we can add that to the bottom of the new `README.md` to assist others attempting a migration when we publish `v0.9`. `image` might be another case study for this I might have a go at if given the go-ahead on https://github.com/image-rs/image/issues/2259 by the maintainers.
