### ISSUE TITLE
Release a `v0.9-alpha.1`?

### ISSUE THREAD

**Issue by ripytide** [kornelski/rust-rgb#113]
I've run out of things on my personal checklist and I don't think any of the repo's remaining open issues are actionable for `v0.9` either:

- #9 i don't really understand
- #25 is now fixed in v0.9
- #36 and #52 seem best left to users to implement themselves
- #39 and #64 are meta-issues
- #46 seems best left to another crate dedicated to pixel conversions as we have discussed in https://github.com/image-rs/canvas/issues/57 which I'm thinking of starting work on after finishing this crate's next release

Therefore, may I suggest (unless you have any outstanding issues/changes?) that now is the time to publish a `v0.9-alpha.1`? After the alpha release is out we can start validating the alpha release by migrating some crates currently depending on `v0.8`. If all goes well then we could proceed with the full release + the semver-trick `v0.8`, if issues are found then we can fix the issues, release another alpha release and repeat the cycle as many times as necessary. How does that sound?

**Comment by kornelski** [comment]
Originally I was thinking about having 0.9 import 0.8 for compatibility, which would give 0.9 alpha releases back-compat. 

But with the semver trick used in the other direction, it may make more sense to start with `v0.8.999-alpha`, so that it can be tested including interaction with 0.8 crates.

**Comment by ripytide** [comment]
Interesting, so you mean releasing the current `0.9` branch as a `v0.8.999-alpha` release since it is non-breaking and so removing the need for a `0.9` release, except for when removing the legacy stuff?

**Comment by kornelski** [comment]
Yes, the current 0.9 needs to be released as 0.8-something to be interoperable with the other 0.8 crates. 0.9 with `legacy` turned on only has source code compatibility, but not backwards-compatible types across crates.

**Comment by kornelski** [comment]
A massive disappointment: Cargo won't unify `v0.8.44` with `v0.8.90-alpha.1`. Not even when requiring `rgb = ">0.7,<0.9"`. 

This complicates testing a lot.
