### ISSUE TITLE
Hex formatting is a mess for >8-bit pixels

### ISSUE THREAD

**Issue by kornelski** [kornelski/rust-rgb#114]
`:02x` assumes max 0xFF, but `Rgba<u16>` can need 4 digits.

**Comment by ripytide** [comment]
I think the simplest fix would be to make make an `impl` for each integer size rather than generically for all component types.

**Comment by ripytide** [comment]
We might have to pull in a dependency for `const_format` to make the macros easier though.

**Comment by kornelski** [comment]
I'm thinking about fudging it: lower hex assumes 2 digits, and upper hex puts spaces or commas between the numbers.

**Comment by ripytide** [comment]
Alternatively, we could just abandon the 2-digit padding entirely, that way it's simple to implement. The main use-case I can think of is CSS-compatable hex color format but that seems best implemented by a user via a custom trait anyway as discussed in #1 and #52.

**Comment by kornelski** [comment]
Oh, `size_of<T>() == 1` could be used to select the CSS hex format!
