### ISSUE TITLE
Should 1-channel Gray still use to/from [v; 1]?

### ISSUE THREAD

**Issue by kornelski** [kornelski/rust-rgb#115]
It seems much more useful to have From/Into that wrap/unwrap `Gray` newtype than to work with 1-channel arrays. 

I don't think these arrays are usable in a generic context, so consistency here may not be necessary?

**Comment by ripytide** [comment]
I'm a bit confused by what you mean but if you mean `impl From<Gray<u8>> for u8` vs `impl From<Gray<u8>> for [u8; 1]`, then my question would be why not offer both?

Related to this is the question of whether we implement the pixel traits for the primitive types? Such as: `impl Pixel for u8`

**Comment by kornelski** [comment]
Can't do both as generic due to overlapping implementations.

**Comment by kornelski** [comment]
Pixel for `u8` would be nice for working with grayscale, but I'm afraid it would more likely cause confusion in code that returns all image data as blobs of unsigned char.

**Comment by ripytide** [comment]
Ah ok, yeah the overlapping implementations is really annoying. The pros of `[T; 1]` are consistency with the other pixel types which might be usable in a generic context:

```rust
use rgb::Pixel;


fn const_generic_function<const N: usize, P>(array: [P::Component; N])
where
    P: Pixel,
    P: From<[P::Component; N]>,
{
    let x = P::try_from_components(array);
}
```

**Comment by kornelski** [comment]
ok, let's keep arrays.
