### ISSUE TITLE
Why so much `doc(hidden)`?

### ISSUE THREAD

**Issue by ripytide** [kornelski/rust-rgb#127]
I've noticed you've `doc(hidden)` a lot of items in the crate for some of the legacy items. Would it not be better to keep them visible and instead deprecate them with an explanation to users why to move away from it?

Otherwise there's the possibility that users can't find a method on the docs.rs page that is already being used in a legacy codebase and so can't learn about it (even if it is discouraged from being used/deprecated).

**Comment by kornelski** [comment]
The compiler will warn users about the deprecated items whenever they're used. This is much easier than manually looking up what's deprecated.

I've put `doc(hidden)` on trivial items that don't need documentation. This reduces chance that new users will find these items in docs and start using them. It also makes the docs less noisy.
