### ISSUE TITLE
Reverse Dependency Backwards Compatability Testing

### ISSUE THREAD

**Issue by ripytide** [kornelski/rust-rgb#129]
I've tested some of the most popular reverse dependencies of `rgb` to test the main branch's backwards compatibility:

- `inferno`: Compiles but some tests fail due to formatting differences, not a big deal as inferno can re-generate it's test results but we could also revert our formatting back to no-spaces.
```
If you have modified the code and specifically want to update the expected test output, set `INFERNO_BLESS_TESTS=1` before the `cargo test`.

Diff < left / right > :
<    <text id="title" fill="rgb(0, 0, 0)" x="50.0000%" y="24.00">Flame Graph</text>
>    <text id="title" fill="rgb(0,0,0)" x="50.0000%" y="24.00">Flame Graph</text>
```

- `image`: Compiles and all tests pass.
- `gif-dispose`: Compiles and all tests pass.
- `ravif`: Compiles and all tests pass, gives deprecation warnings about types being renamed.
- `resvg`: Compiles, has no tests.
- `femtovg`: Compiles, fails the same tests with and without patching with the new `rgb` branch so seems like an unrelated bug or user-error on my part.
- `lodepng`: Compiles, fails the same test with and without patching with the new `rgb` branch so seems like an unrelated bug or user-error on my part.
- `csscolorparser` + `rust-rgb` feature: Compiles and all tests pass, gives deprecation warnings about types being renamed.
- `ansi_colours`: Bingo! Spits out two types of compiler errors when using the new `rgb` branch:
```
error[E0308]: mismatched types
  --> /home/ripytide/.cargo/registry/src/index.crates.io-6f17d22bba15001f/empfindung-0.2.6/src/to_lab_impls.rs:45:57
   |
45 |     fn to_lab(&self) -> (f32, f32, f32) { lab_from_grey(**self) }
   |                                           ------------- ^^^^^^ expected `u8`, found `Gray_v09<u8>`
   |                                           |
   |                                           arguments to this function are incorrect
   |
   = note: expected type `u8`
            found struct `Gray_v09<u8>`
note: function defined here
  --> /home/ripytide/.cargo/registry/src/index.crates.io-6f17d22bba15001f/empfindung-0.2.6/src/to_lab_impls.rs:55:4
   |
55 | fn lab_from_grey(grey: u8) -> (f32, f32, f32) {
   |    ^^^^^^^^^^^^^ --------



error[E0599]: no method named `into_u8` found for reference `&Gray<C>` in the current scope
  --> src/impls.rs:78:36
   |
78 |     fn as_u32(&self) -> u32 { self.into_u8() as u32 * 0x010101 }
   |                                    ^^^^^^^
   |
   = help: items from traits can only be used if the trait is implemented and in scope
note: `Component` defines an item `into_u8`, perhaps you need to implement it
  --> src/impls.rs:28:1
   |
28 | trait Component: Copy {
   | ^^^^^^^^^^^^^^^^^^^^^
help: one of the expressions' fields has a method of the same name
   |
78 |     fn as_u32(&self) -> u32 { self.0.into_u8() as u32 * 0x010101 }
   |                                    ++
help: one of the expressions' fields has a method of the same name
   |
78 |     fn as_u32(&self) -> u32 { self.v.into_u8() as u32 * 0x010101 }
   |                                    ++
help: there is a method `into` with a similar name
   |
78 |     fn as_u32(&self) -> u32 { self.into() as u32 * 0x010101 }
```
The root cause seems to be the lack of a `Deref<Target=T>` for the `Gray_v08` types since we made it implement `Deref<Target=Gray_v09>` instead, we might have to revert back to the old `Deref` implementation.

- `i-slint-core`: Compiles, fails the same tests with and without patching with the new `rgb` branch as I don't have one of the test fonts installed.

**Comment by kornelski** [comment]
The `mss_saliency` crate didn't work without the legacy `From` impls, because it depends on `RGB<u32>: From<RGB<u8>>`. 

https://github.com/kornelski/mss_saliency/blob/2e685c5f5c247d7e73c261b2fb46f02c08b2e7fe/src/lib.rs#L18;L23

**Comment by kornelski** [comment]
`use rgb::*; use rgb::alt::*; GRAY8` breaks, because it's defined in two places differently.

**Comment by ripytide** [comment]
Those two issues seem like they would require major rework to fix, is it worth the effort to fix those backwards incompatibilities or can we simply expect users to fix those issues themselves after we release `v0.8.90`?

I think we should release `v0.8.90` as is given we've attempted backwards compatibility on a best-effort basis, how about you?

**Comment by kornelski** [comment]
I've removed spaces from `Display`.

**Comment by kornelski** [comment]
Unfortunately Rust can't display deprecations for uses of `Deref`, so moving users away from Gray's deref will be tricky.

**Comment by ripytide** [comment]
Hopefully the `Deref` issue won't be that bad as eventually `Gray_v08` will be deprecated so they can migrate away from `Deref` at the same time they migrate to `Gray_v09`.

**Comment by kornelski** [comment]
Now it's impossible to future-proof access to `Gray` due to the `.0` field and lack of Deref. Maybe both types should get `.v()` or `.value()` getter?

There's also no `Rgb::from(gray)`
