### ISSUE TITLE
as_mut_slice is confusing on Vec

### ISSUE THREAD

**Issue by kornelski** [kornelski/rust-rgb#14]
`Vec` has its own `as_mut_slice`, so the method call is ambiguous on `Vec<RGB<T>>` and causes annoying type errors.

It needs a different name. `as_mut_component_slice()` is kinda long :/

**Comment by ripytide** [comment]
I'd be in favor of changing the name despite making it longer since readability is often more important than function length.

If #65 is accepted this would also become 1 character shorter to `as_mut_subpixel_slice()` :smile:.

**Comment by ripytide** [comment]
This issue seems to be in contradiction with #70 since this method would no longer exist in the crate if those traits are removed. I'd recommend this being closed.
