### ISSUE TITLE
Support for non-power-of-two colour values?

### ISSUE THREAD

**Issue by ketsuban** [kornelski/rust-rgb#20]
Here are some colour representations I know about.

* On the Megadrive, colour is 9-bit, with three bits per colour, blue first (`0b0000_BBB0_GGG0_RRR0`). The hardware has no support for alpha transparency, but it's not outside the realm of possibility that a software implementation might store it in the high nybble of a colour word.
* On the Game Boy Advance, colour is 15-bit, with five bits per colour, blue first (`0b0_BBBBB_GGGGG_RRRRR`).

Is it feasible for the `rgb` crate to support formats like these, or should they be considered out of scope?

**Comment by kornelski** [comment]
Unfortunately, because RGB is a struct, it requires each component to be byte-aligned.

So it is out of scope. 

You could still add `Info`/`From` conversion implementations to pack and unpack these colors for easier processing.
