### ISSUE TITLE
Add support for ARGB/ABGR alternative order and xRGB variants

### ISSUE THREAD

**Issue by sdroege** [kornelski/rust-rgb#29]
See summary :)

**Comment by kornelski** [comment]
Uh, that adds quite a number of permutations. I presume you have to work with a system that has these types and they can't be avoided?

**Comment by sdroege** [comment]
Cairo for example is ARGB on big endian systems and BGRA on little endian systems (`CAIRO_FORMAT_ARGB32`) and the non-alpha variant is the same but simply ignores the alpha value (`CAIRO_FORMAT_RGB24`).

If you don't want to support all those permutations that's also fine, I can continue using my own code for this instead of using this crate :)

**Comment by kornelski** [comment]
It's on master behind a feature flag. Let me know if that works for you.
