### ISSUE TITLE
Color dispay formatting

### ISSUE THREAD

**Issue by kornelski** [kornelski/rust-rgb#3]
Hex formatting seems like a nice to have:

https://github.com/rust-lang-nursery/rust-api-guidelines#c-num-fmt

**Comment by RazrFalcon** [comment]
New link: https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#binary-number-types-provide-hex-octal-binary-formatting-c-num-fmt

**Comment by cole-miller** [comment]
Looks like this was implemented in #24
