### ISSUE TITLE
BGR::new is confusing

### ISSUE THREAD

**Issue by RazrFalcon** [kornelski/rust-rgb#32]
Turns out that `BGR::new(255, 0, 0)` actually means `BGR { b: 0 g: 0 r: 255  }`, not `BGR { b: 255 g: 0 r: 0  }`. I understand that this is a breaking change, but maybe this should be changed/fixed?

**Comment by kornelski** [comment]
Yeah, that's a mistake.

**Comment by RazrFalcon** [comment]
Thanks.
