### ISSUE TITLE
feature: option to convert color to html code

### ISSUE THREAD

**Issue by LuckyTurtleDev** [kornelski/rust-rgb#52]
It would be nice if it will be possible to convert the color to html.

Some thing like this:
```rust
let color = RGB8 { r: 255, g: 0, b: 0 };
println("color: {}", color.to_html());
```
```
color: #ff0000
```

**Comment by rursprung** [comment]
this is pretty easy to implement (code w/o dependency on `rgb` as it's not available on the playground):
```rust
fn main() {
    let rgb = [255 as u8, 2 as u8, 1 as u8];
    println!("RGB ({}, {}, {}) = #{:0>2x}{:0>2x}{:0>2x}", rgb[0], rgb[1], rgb[2], rgb[0], rgb[1], rgb[2]);
}
```

output:
```
RGB (255, 2, 1) = #ff0201
```

see [on the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c3826d14ffb546f7c37839f06e3602c3).

**Comment by ripytide** [comment]
Related to #1. This seems out of scope of this project.

It is easy to implement for the end user:
```rust
pub trait ToHtml {
    fn to_html() -> String;
}
impl ToHtml for Rgb<u8> {
    ...
}
```

I'd recommend closing this.
