### ISSUE TITLE
GRB

### ISSUE THREAD

**Issue by chrisprice** [kornelski/rust-rgb#55]
I've been looking into ws2812 compatible LEDs and (seemingly at random) many (but not all) manufacturers have picked GRB as their byte level ordering [(example encoder)](https://github.com/rp-rs/ws2812-pio-rs/blob/main/src/lib.rs#L174). As there are already alternative encodings supported, is there any appetite for supporting this encoding (as well as an alpha and reversed versions)?

**Comment by kornelski** [comment]
Yeah, why not.

**Comment by chrisprice** [comment]
Thanks!
