### ISSUE TITLE
Create a `v0.9` branch

### ISSUE THREAD

**Issue by ripytide** [kornelski/rust-rgb#63]
Greetings, I would like to take a shot at working on an `v0.9` as I currently have the time+motivation for it. My goals would be to implement all the currently discussed improvements from the issue tracker.

Since this would inherently require breaking changes, simply making a series of pull requests to the main branch may not be a viable option as it would prevent any changes to `v0.8` (like for the `semver-trick`). Instead, may I suggest the creation of another branch for `v0.9` with which I can submit PRs to?

**Comment by kornelski** [comment]
Yeah. Thanks in advance!
