### ISSUE TITLE
Change word `component` to `subpixel`.

### ISSUE THREAD

**Issue by ripytide** [kornelski/rust-rgb#65]
Should we change the word `component` to `subpixel` throughout the library?
It is both shorter and more recognizable/understandable in my opinion.

This also goes nicely with a possible `Pixel` trait discussed in https://github.com/kornelski/rust-rgb/issues/39#issuecomment-835298062

**Comment by ripytide** [comment]
Good point.

On the other hand `Subpixel` has already used somewhat from the `image` crate in their [`Pixel`](https://docs.rs/image/latest/image/trait.Pixel.html#) trait as an associated type.

**Comment by kornelski** [comment]
It looks more a mistake in the image crate - they use `CHANNEL_COUNT` and `channel()` to work with "Subixels".

**Comment by ripytide** [comment]
And yet their pixel types like `Rgba` use interleaved format which contradicts your channels being planar layout logic, odd.

**Comment by kornelski** [comment]
It could be worse. In the era of CRT monitors they were called "gun" (as in electron gun), "VGA has 6 bits per gun".

**Comment by ripytide** [comment]
According to the [Pixel](https://en.wikipedia.org/wiki/Pixel#Subpixels) wikipedia page industries also calls "Subpixels" as just "Pixels":

> In display industry terminology, subpixels are often referred to as pixels, as they are the basic addressable elements in a viewpoint of hardware, and hence pixel circuits rather than subpixel circuits is used.

**Comment by ripytide** [comment]
The word "component" is sadly also not free from confusion: https://en.wikipedia.org/wiki/Component_video. :frowning_face:

**Comment by kornelski** [comment]
Component video is named correctly, and that's the same kind of component as pixel components.

**Comment by ripytide** [comment]
Does that mean that `alpha` is not considered a component of a pixel?

**Comment by ripytide** [comment]
We could do both if we are making two traits:
```rust
pub trait Pixel {
fn subpixels(&self) -> [T; 3];
}

pub trait AlphaPixel {
fn components(&self) -> [T; 4];
}
```

This would then fit with the *alpha is not a subpixel* logic while still using the "component` word when alpha is involved?

**Comment by kornelski** [comment]
No. Let me be clear: subpixel is an incorrect term for this, and use of this term in the image crate is an error. It [describes hardware](https://en.wikipedia.org/wiki/Pixel#Subpixels). Terms like "[subpixel rendering](https://en.wikipedia.org/wiki/Subpixel_rendering)" are dependent on physical properties of the hardware they target. This term would make sense in a display driver, but this crate is more abstract than that. There's also "sub-pixel precision" (sub-pel), but this refers to rendering methods, not the channels/components.

RGB as a [color model](https://en.wikipedia.org/wiki/Color_model) uses [components](https://en.wikipedia.org/wiki/RGB_color_model). The term `channel` could also be okay, `component` and `channel` are often used interchangeably, except that `channel` is more strongly associated with a planar color layout where each channel is a separate monochrome image with intensities for a color component.

**Comment by ripytide** [comment]
Okay that makes sense to me. I'll no longer use the word "subpixel".

I'll experiment a bit more with the two-trait method a bit more, though I suspect we'll still need two different names for returning arrays of non-alpha components and alpha-inclusive components.
