### ISSUE TITLE
Allow `docs.rs` to auto-label optional features.

### ISSUE THREAD

**Issue by ripytide** [kornelski/rust-rgb#68]
See rustdoc documentation on it at https://doc.rust-lang.org/rustdoc/unstable-features.html#doc_auto_cfg-automatically-generate-doccfg

This should fix #34

**Comment by ripytide** [comment]
I'm confused by what you mean by verbose?

This is what I see using `#![feature(doc_auto_cfg)]` for the `GRB` page:
![image](https://github.com/kornelski/rust-rgb/assets/62516857/c1aee978-74ba-40ba-85f2-1752b4eef9f0)
Vs without:
![image](https://github.com/kornelski/rust-rgb/assets/62516857/c2379ce1-d343-4a92-8e28-1ed3055869f9)

**Comment by kornelski** [comment]
Examples in the linked rustdoc issue looked worse and printed raw cfg expressions. Maybe it's been fixed since?

**Comment by ripytide** [comment]
Oh I see the issue in https://github.com/rust-lang/rust/issues/43781, yeah the example given there does look quite verbose but I think they've mostly fixed it by now.

Here is the listing page which I think is very manageable:
![image](https://github.com/kornelski/rust-rgb/assets/62516857/38bef04f-7e56-4062-96bc-1f217ca0e62f)
