### ISSUE TITLE
Remove the `ComponentBytes` and `AsPixels` traits

### ISSUE THREAD

**Issue by ripytide** [kornelski/rust-rgb#70]
I don't see the utility of the `ComponentBytes` and `AsPixels` traits compared to a user simply using `bytemuck`'s `cast_slice()` and `cast_slice_mut()` methods. This could easily be achieved by optionally implementing `bytemuck::Pod` for all the pixel structs. Then a user could enable that crate-feature and use `bytemuck` to do conversions as they need.

In addition, having an crate-local implementation has had soundness flaws in the past in #35 so removing it would reduce that risk.

**Comment by ripytide** [comment]
Also mentioned in https://github.com/kornelski/rust-rgb/issues/39#issuecomment-835298062

**Comment by kornelski** [comment]
The only issue is that bytemuck's syntax is more verbose, since `cast_slice()` etc are not trait methods, but standalone functions in the bytemuck crate.
