### ISSUE TITLE
Consider specifying the meaning of alpha values

### ISSUE THREAD

**Issue by stephaneyfx** [kornelski/rust-rgb#8]
Does specifying the meaning of alpha values seem reasonable and something you would consider accepting a PR for? I'm thinking about stating that alpha values represent opacity, and so for example 255 is fully opaque for RGBA8.

Currently the documentation of RGBA8 indicates that the crate does not impose which value represents transparency, though it does state what it usually is.

I think that this lack of commitment may fail to detect bugs if this crate is to be used between other crates that adopt incompatible interpretations of the alpha field. That's why I would like to suggest doing the following:

* Amend the doc of RGBA8 to indicate that the alpha field represents opacity and 255 means fully opaque.
* State in the crate documentation that alpha values represent opacity and that for integer alpha values, the maximum value of the underlying type represents full opacity.
* Optionally define a newtype wrapper like `InvAlpha<T>` or `Transparency<T>` for cases where the greatest value should mean fully transparent.

I think this would help to catch bugs at compile-time and make this crate more robust to be used as a building block between other imaging crates. What do you think?

**Comment by kornelski** [comment]
I wanted to be completely agnostic about it in case someone needs to work with some silly format with 0=opaque. 

In retrospect, it doesn't seem like a strong use case, so I think it's fine to define opaque as `255` for `u8`.

**Comment by stephaneyfx** [comment]
Great! Thank you.
